# Generated by Django 5.1.4 on 2024-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_ikan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikan',
            name='gambar',
            field=models.CharField(max_length=500),
        ),
    ]
